export const orderData = [
  {
    id: 1,
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    quantity: 4,
    brand: 'Apple',
    category: 'smartphones',
  },
  {
    id: 2,
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    quantity: 4,
    stock: 94,
    brand: 'Apple',
    category: 'smartphones',
  },
  {
    id: 1,
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    quantity: 4,
    brand: 'Apple',
    category: 'smartphones',
  },
  {
    id: 2,
    title: 'samsung',
    description: 'An samsung mobile which is nothing like samsung',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    quantity: 4,
    stock: 94,
    brand: 'Samsung',
    category: 'smartphones',
  },
  {
    id: 1,
    title: 'Redmi',
    description: 'An redmi mobile which is nothing like redmi',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    quantity: 4,
    brand: 'Redmi',
    category: 'smartphones',
  },
  {
    id: 2,
    title: 'realme',
    description: 'An realme mobile which is nothing like realme',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    quantity: 4,
    stock: 94,
    brand: 'Realme',
    category: 'smartphones',
  },
]
